---
name: CI
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
defaults:
  run:
    working-directory: 'hoprnet.certbot'
jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout ansible role'
        uses: actions/checkout@v2
        with:
          path: 'hoprnet.certbot'
      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install test dependencies.
        run: pip3 install ansible molecule[docker] docker
      - name: Force GitHub Actions' docker daemon to use vfs.
        run: |
          sudo systemctl stop docker
          echo '{"cgroup-parent":"/actions_job","storage-driver":"vfs"}' | \
          sudo tee /etc/docker/daemon.json
          sudo systemctl start docker
          sudo systemctl status docker
          cat /etc/docker/daemon.json
      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DEBUG: 1
          ANSIBLE_VERBOSITY: 4
          RUNNING_ON_GITHUB: true
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'hoprnet.certbot'
      - name: Install test dependencies.
        run: pip3 install yamllint ansible-lint
      - name: Yaml Lint code.
        run: |
          yamllint .
      - name: Ansible Lint code.
        run: |
          ansible-lint --exclude ~/.ansible/roles
